# Generated by Django 2.1.2 on 2019-10-15 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=10000)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('existence', models.BooleanField(default=True)),
                ('product_type', models.PositiveSmallIntegerField(choices=[(1, 'T-SHIRT'), (2, 'PANTS'), (3, 'HOODEY'), (4, 'COAT')], default=1)),
                ('size', models.PositiveSmallIntegerField(choices=[(1, 'S'), (2, 'M'), (3, 'L'), (4, 'XL'), (5, 'XXL')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=10000)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('aproximate_duration', models.DateField()),
                ('service_type', models.PositiveSmallIntegerField(choices=[(1, 'DELIVERY'), (2, 'SUBSCRIPTION')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
