PRODUCT_SMALL = 1
PRODUCT_MED = 2
PRODUCT_LARGE = 3
PRODUCT_XLARGE = 4
PRODUCT_XXLARGE = 5

PRODUCT_SIZES = (
    (PRODUCT_SMALL, 'S'),
    (PRODUCT_MED, 'M'),
    (PRODUCT_LARGE, 'L'),
    (PRODUCT_XLARGE, 'XL'),
    ((PRODUCT_XXLARGE), 'XXL'),
)

PRODUCT_TSHIRT = 1
PRODUCT_PANTS = 2
PRODUCT_HOODEY = 3
PRODUCT_COAT = 4

PRODUCT_TYPES = (
    (PRODUCT_TSHIRT, 'T-SHIRT'),
    (PRODUCT_PANTS, 'PANTS'),
    (PRODUCT_HOODEY, 'HOODEY'),
    (PRODUCT_COAT, 'COAT'),
)

SERVICE_DELIVERY = 1
SERVICE_SUBSCRIPTION = 2

SERVICE_TYPES = (
    (SERVICE_DELIVERY, 'DELIVERY'),
    (SERVICE_SUBSCRIPTION, 'SUBSCRIPTION')
)